project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - analysis.qmd

website:
  title: "HPD 685 Linear Longitudinal Modeling"
  site-url: "https://crystalbell98.github.io/HPD685-Notes"
  navbar:
    left:
      - href: index.qmd
        text: Longitudinal Modeling Notes
      - href: analysis.qmd
        text: R Code Examples

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: left
    toc-title: "目录"
    number-sections: true
    smooth-scroll: true
    highlight-style: github
    code-fold: true
    mainfont: "Noto Serif SC, serif"
    monofont: "Fira Code, monospace"
    css: styles.css
